// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var Header$ReactTemplate = require("./Header.bs.js");
var HelpModal$ReactTemplate = require("./HelpModal.bs.js");
var GearingModal$ReactTemplate = require("./GearingModal.bs.js");

var component = ReasonReact.reducerComponent("App-ReactTemplate");

function make(_children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (self) {
              return React.createElement(React.Fragment, undefined, ReasonReact.element(undefined, undefined, Header$ReactTemplate.make((function (_event) {
                                    return Curry._1(self[/* send */3], /* ModalOpen */[/* Gearing */0]);
                                  }), (function (_event) {
                                    return Curry._1(self[/* send */3], /* ModalOpen */[/* Help */1]);
                                  }), /* array */[])), ReasonReact.element(undefined, undefined, HelpModal$ReactTemplate.make(/* array */[], self[/* state */1][/* modal */0] === /* Help */1, (function (_event) {
                                    return Curry._1(self[/* send */3], /* ModalClose */0);
                                  }))), ReasonReact.element(undefined, undefined, GearingModal$ReactTemplate.make(/* array */[], self[/* state */1][/* modal */0] === /* Gearing */0, (function (_event) {
                                    return Curry._1(self[/* send */3], /* ModalClose */0);
                                  }))));
            }),
          /* initialState */(function (param) {
              return /* record */[/* modal : None */2];
            }),
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */(function (action, state) {
              if (action) {
                return /* Update */Block.__(0, [/* record */[/* modal */action[0]]]);
              } else {
                return /* Update */Block.__(0, [/* record */[/* modal : None */2]]);
              }
            }),
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
