// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var $$String = require("bs-platform/lib/js/string.js");
var Belt_List = require("bs-platform/lib/js/belt_List.js");
var Pervasives = require("bs-platform/lib/js/pervasives.js");
var Caml_string = require("bs-platform/lib/js/caml_string.js");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var MaterialUi_Button = require("@jsiebern/bs-material-ui/lib/js/src/MaterialUi_Button.bs.js");
var MaterialUi_Dialog = require("@jsiebern/bs-material-ui/lib/js/src/MaterialUi_Dialog.bs.js");
var MaterialUi_Select = require("@jsiebern/bs-material-ui/lib/js/src/MaterialUi_Select.bs.js");
var MaterialUi_Switch = require("@jsiebern/bs-material-ui/lib/js/src/MaterialUi_Switch.bs.js");
var MaterialUi_MenuItem = require("@jsiebern/bs-material-ui/lib/js/src/MaterialUi_MenuItem.bs.js");
var MaterialUi_InputLabel = require("@jsiebern/bs-material-ui/lib/js/src/MaterialUi_InputLabel.bs.js");
var MaterialUi_WithStyles = require("@jsiebern/bs-material-ui/lib/js/src/MaterialUi_WithStyles.bs.js");
var MaterialUi_DialogTitle = require("@jsiebern/bs-material-ui/lib/js/src/MaterialUi_DialogTitle.bs.js");
var Caml_builtin_exceptions = require("bs-platform/lib/js/caml_builtin_exceptions.js");
var MaterialUi_DialogActions = require("@jsiebern/bs-material-ui/lib/js/src/MaterialUi_DialogActions.bs.js");
var MaterialUi_DialogContent = require("@jsiebern/bs-material-ui/lib/js/src/MaterialUi_DialogContent.bs.js");
var GearingValues$ReactTemplate = require("./GearingValues.bs.js");
var MaterialUi_DialogContentText = require("@jsiebern/bs-material-ui/lib/js/src/MaterialUi_DialogContentText.bs.js");

var component = ReasonReact.reducerComponent("GearingModal-ReactTemplate");

function formatFloat(str) {
  var len = str.length;
  var lastChar = Caml_string.get(str, len - 1 | 0);
  if (lastChar === /* "." */46) {
    return $$String.sub(str, 0, len - 1 | 0);
  } else {
    return str;
  }
}

function classRecordToJs(param) {
  return {
          field: param[/* field */0]
        };
}

var classes = /* Record */Block.__(0, [/* record */[/* field */{
        marginBottom: "1.5em"
      }]]);

function classRecordStringsFromJs(arg) {
  return /* record */[/* field */arg.field];
}

var StyleDefs = /* module */[
  /* classRecordToJs */classRecordToJs,
  /* classRecordStringsFromJs */classRecordStringsFromJs,
  /* classes */classes
];

var Style = MaterialUi_WithStyles.WithStylesSafe(StyleDefs);

function make(_children, visible, handleClose) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (self) {
              return ReasonReact.element(undefined, undefined, Curry._1(Style[/* make */4], (function (classes) {
                                return React.createElement(React.Fragment, undefined, ReasonReact.element(undefined, undefined, MaterialUi_Dialog.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, (function (_event) {
                                                      return Curry._1(handleClose, /* () */0);
                                                    }), undefined, undefined, undefined, undefined, (function (_event) {
                                                      return Curry._1(handleClose, /* () */0);
                                                    }), undefined, undefined, undefined, visible, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* array */[
                                                    ReasonReact.element(undefined, undefined, MaterialUi_DialogTitle.make(undefined, undefined, undefined, undefined, /* array */["Enter your details"])),
                                                    ReasonReact.element(undefined, undefined, MaterialUi_DialogContent.make(undefined, undefined, undefined, /* array */[
                                                              ReasonReact.element(undefined, undefined, MaterialUi_DialogContentText.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, true, undefined, undefined, undefined, /* array */["Enter your component details below to calculate your gearing."])),
                                                              ReasonReact.element(undefined, undefined, MaterialUi_InputLabel.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* array */["Chainring"])),
                                                              ReasonReact.element(undefined, undefined, MaterialUi_Select.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* `Int */[
                                                                        3654863,
                                                                        self[/* state */1][/* chainringTeeth */0]
                                                                      ], undefined, undefined, undefined, classes[/* field */0], undefined, undefined, undefined, undefined, undefined, true, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* array */[Belt_List.map(GearingValues$ReactTemplate.chainringTeeth, (function (teeth) {
                                                                                return ReasonReact.element(undefined, undefined, MaterialUi_MenuItem.make(undefined, undefined, undefined, undefined, undefined, /* `Int */[
                                                                                                3654863,
                                                                                                teeth
                                                                                              ], undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* array */[React.createElement("em", undefined, String(teeth))]));
                                                                              }))])),
                                                              ReasonReact.element(undefined, undefined, MaterialUi_InputLabel.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* array */["Cog"])),
                                                              ReasonReact.element(undefined, undefined, MaterialUi_Select.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* `Int */[
                                                                        3654863,
                                                                        self[/* state */1][/* cogTeeth */1]
                                                                      ], undefined, undefined, undefined, classes[/* field */0], undefined, undefined, undefined, undefined, undefined, true, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* array */[Belt_List.map(GearingValues$ReactTemplate.cogTeeth, (function (teeth) {
                                                                                return ReasonReact.element(undefined, undefined, MaterialUi_MenuItem.make(undefined, undefined, undefined, undefined, undefined, /* `Int */[
                                                                                                3654863,
                                                                                                teeth
                                                                                              ], undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* array */[React.createElement("em", undefined, String(teeth))]));
                                                                              }))])),
                                                              ReasonReact.element(undefined, undefined, MaterialUi_InputLabel.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* array */["Wheel Size"])),
                                                              ReasonReact.element(undefined, undefined, MaterialUi_Select.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* `String */[
                                                                        -976970511,
                                                                        self[/* state */1][/* wheelSize */2]
                                                                      ], undefined, undefined, undefined, classes[/* field */0], undefined, undefined, undefined, undefined, undefined, true, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* array */[Belt_List.map(GearingValues$ReactTemplate.wheelSizes, (function (param) {
                                                                                return ReasonReact.element(undefined, undefined, MaterialUi_MenuItem.make(undefined, undefined, undefined, undefined, undefined, /* `String */[
                                                                                                -976970511,
                                                                                                param[/* key */2]
                                                                                              ], undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* array */[React.createElement("em", undefined, param[/* name */0])]));
                                                                              }))])),
                                                              ReasonReact.element(undefined, undefined, MaterialUi_InputLabel.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* array */["Crank Length"])),
                                                              ReasonReact.element(undefined, undefined, MaterialUi_Select.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* `Float */[
                                                                        365180284,
                                                                        self[/* state */1][/* crankLength */3]
                                                                      ], undefined, undefined, undefined, classes[/* field */0], undefined, undefined, undefined, undefined, undefined, true, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* array */[Belt_List.map(GearingValues$ReactTemplate.crankLengths, (function (length) {
                                                                                return ReasonReact.element(undefined, undefined, MaterialUi_MenuItem.make(undefined, undefined, undefined, undefined, undefined, /* `Float */[
                                                                                                365180284,
                                                                                                length
                                                                                              ], undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* array */[React.createElement("em", undefined, formatFloat(Pervasives.string_of_float(length)))]));
                                                                              }))])),
                                                              ReasonReact.element(undefined, undefined, MaterialUi_InputLabel.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* array */["Ambidextrous Skidder"])),
                                                              ReasonReact.element(undefined, undefined, MaterialUi_Switch.make(/* `Bool */[
                                                                        737456202,
                                                                        self[/* state */1][/* ambidextrousSkidder */4]
                                                                      ], undefined, undefined, /* Primary */-791844958, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* array */[]))
                                                            ])),
                                                    ReasonReact.element(undefined, undefined, MaterialUi_DialogActions.make(undefined, undefined, undefined, undefined, /* array */[
                                                              ReasonReact.element(undefined, undefined, MaterialUi_Button.make(undefined, /* Primary */-791844958, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, (function (_e) {
                                                                          return Curry._1(handleClose, /* () */0);
                                                                        }), undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* array */["Cancel"])),
                                                              ReasonReact.element(undefined, undefined, MaterialUi_Button.make(undefined, /* Primary */-791844958, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, (function (_e) {
                                                                          return Curry._1(self[/* send */3], /* SubmitGearing */0);
                                                                        }), undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* array */["Ok"]))
                                                            ]))
                                                  ])));
                              })));
            }),
          /* initialState */(function (param) {
              return /* record */[
                      /* chainringTeeth */46,
                      /* cogTeeth */16,
                      /* wheelSize */"27-nom",
                      /* crankLength */165,
                      /* ambidextrousSkidder */false
                    ];
            }),
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */(function (action, state) {
              if (typeof action === "number") {
                return /* SideEffects */Block.__(1, [(function (_self) {
                              console.log("hello");
                              return Curry._1(handleClose, /* () */0);
                            })]);
              } else {
                throw [
                      Caml_builtin_exceptions.match_failure,
                      /* tuple */[
                        "GearingModal.re",
                        46,
                        4
                      ]
                    ];
              }
            }),
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.component = component;
exports.formatFloat = formatFloat;
exports.StyleDefs = StyleDefs;
exports.Style = Style;
exports.make = make;
/* component Not a pure module */
