// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Belt_List = require("bs-platform/lib/js/belt_List.js");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");

var chainringTeeth = Belt_List.fromArray(Belt_Array.range(28, 59));

var cogTeeth = Belt_List.fromArray(Belt_Array.range(9, 23));

var wheelSizes = /* :: */[
  /* record */[
    /* name */"29 inch (nominal)",
    /* value */29
  ],
  /* :: */[
    /* record */[
      /* name */"28 inch (nominal)",
      /* value */28
    ],
    /* :: */[
      /* record */[
        /* name */"27 inch (nominal)",
        /* value */27
      ],
      /* :: */[
        /* record */[
          /* name */"26 inch (nominal)",
          /* value */26
        ],
        /* :: */[
          /* record */[
            /* name */"700 X 56 / 56-622 / 29 inch",
            /* value */29.13
          ],
          /* :: */[
            /* record */[
              /* name */"700 X 50 / 50-622 / 29 inch",
              /* value */28.94
            ],
            /* :: */[
              /* record */[
                /* name */"700 X 44 / 44-622 / 29 inch",
                /* value */27.86
              ],
              /* :: */[
                /* record */[
                  /* name */"700 X 38 / 38-622",
                  /* value */27.32
                ],
                /* :: */[
                  /* record */[
                    /* name */"700 X 35 / 35-622",
                    /* value */27.17
                  ],
                  /* :: */[
                    /* record */[
                      /* name */"700 X 32 / 32-622 ",
                      /* value */27
                    ],
                    /* :: */[
                      /* record */[
                        /* name */"700 X 28 / 28-622",
                        /* value */26.76
                      ],
                      /* :: */[
                        /* record */[
                          /* name */"700 X 25 / 25-622",
                          /* value */26.38
                        ],
                        /* :: */[
                          /* record */[
                            /* name */"700 X 23 / 23-622",
                            /* value */26.28
                          ],
                          /* :: */[
                            /* record */[
                              /* name */"700 X 20 / 20-622",
                              /* value */26.14
                            ],
                            /* :: */[
                              /* record */[
                                /* name */"Tubular / Wide",
                                /* value */26.53
                              ],
                              /* :: */[
                                /* record */[
                                  /* name */"Tubular / Narrow",
                                  /* value */26.38
                                ],
                                /* :: */[
                                  /* record */[
                                    /* name */"28 X 1 1/2 / 40-635 ",
                                    /* value */28.15
                                  ],
                                  /* :: */[
                                    /* record */[
                                      /* name */"27 X 1 3/8 / 35-630",
                                      /* value */27.18
                                    ],
                                    /* :: */[
                                      /* record */[
                                        /* name */"27 X 1 1/4 / 32-630",
                                        /* value */27.08
                                      ],
                                      /* :: */[
                                        /* record */[
                                          /* name */"27 X 1 1/8 / 28-630",
                                          /* value */27
                                        ],
                                        /* :: */[
                                          /* record */[
                                            /* name */"27 X 1 / 25-630",
                                            /* value */26.88
                                          ],
                                          /* :: */[
                                            /* record */[
                                              /* name */"26 X 2.35 / 60-559 / MTB",
                                              /* value */26.41
                                            ],
                                            /* :: */[
                                              /* record */[
                                                /* name */"26 X 2.125 / 54-559 / MTB",
                                                /* value */25.94
                                              ],
                                              /* :: */[
                                                /* record */[
                                                  /* name */"26 X 1.9 / 47-559 / MTB",
                                                  /* value */25.75
                                                ],
                                                /* :: */[
                                                  /* record */[
                                                    /* name */"26 X 1.5 / 38-559 / MTB",
                                                    /* value */24.87
                                                  ],
                                                  /* :: */[
                                                    /* record */[
                                                      /* name */"26 X 1.25 / 32-559 / MTB",
                                                      /* value */24.47
                                                    ],
                                                    /* :: */[
                                                      /* record */[
                                                        /* name */"26 X 1.0 / 25-559 / MTB",
                                                        /* value */23.97
                                                      ],
                                                      /* :: */[
                                                        /* record */[
                                                          /* name */"650 x 38b / 38-584 650B",
                                                          /* value */26
                                                        ],
                                                        /* :: */[
                                                          /* record */[
                                                            /* name */"650 x 28C / 28-571 / 26' road/tri",
                                                            /* value */24.7
                                                          ],
                                                          /* :: */[
                                                            /* record */[
                                                              /* name */"650 x 25C / 25-571 / 26' road/tri",
                                                              /* value */24.46
                                                            ],
                                                            /* :: */[
                                                              /* record */[
                                                                /* name */"650 x 23C / 23-571 / 26' road/tri",
                                                                /* value */24.31
                                                              ],
                                                              /* :: */[
                                                                /* record */[
                                                                  /* name */"26 X 1 3/8 / 35-590",
                                                                  /* value */25.91
                                                                ],
                                                                /* :: */[
                                                                  /* record */[
                                                                    /* name */"24 inch (nominal)",
                                                                    /* value */24
                                                                  ],
                                                                  /* :: */[
                                                                    /* record */[
                                                                      /* name */"24 x 1 / 25-520",
                                                                      /* value */21.97
                                                                    ],
                                                                    /* :: */[
                                                                      /* record */[
                                                                        /* name */"32-451 /20 x 1 3/8",
                                                                        /* value */20.15
                                                                      ],
                                                                      /* :: */[
                                                                        /* record */[
                                                                          /* name */"28-451/20 x 1 1/8",
                                                                          /* value */19.9
                                                                        ],
                                                                        /* :: */[
                                                                          /* record */[
                                                                            /* name */"20 X 1.75 / 44-406 / BMX",
                                                                            /* value */18.68
                                                                          ],
                                                                          /* :: */[
                                                                            /* record */[
                                                                              /* name */"20 X 1.25 / 32-406",
                                                                              /* value */18.43
                                                                            ],
                                                                            /* :: */[
                                                                              /* record */[
                                                                                /* name */"18 x 1.5 / 40-355",
                                                                                /* value */17.16
                                                                              ],
                                                                              /* :: */[
                                                                                /* record */[
                                                                                  /* name */"17 x 1 1/4 / 28-369",
                                                                                  /* value */16.6
                                                                                ],
                                                                                /* :: */[
                                                                                  /* record */[
                                                                                    /* name */"16 x 1 1/2 / 40-349",
                                                                                    /* value */16.88
                                                                                  ],
                                                                                  /* :: */[
                                                                                    /* record */[
                                                                                      /* name */"16 x 1 3/8 / 35-349",
                                                                                      /* value */16.07
                                                                                    ],
                                                                                    /* :: */[
                                                                                      /* record */[
                                                                                        /* name */"16 x 1.5 / 37-305",
                                                                                        /* value */13.46
                                                                                      ],
                                                                                      /* [] */0
                                                                                    ]
                                                                                  ]
                                                                                ]
                                                                              ]
                                                                            ]
                                                                          ]
                                                                        ]
                                                                      ]
                                                                    ]
                                                                  ]
                                                                ]
                                                              ]
                                                            ]
                                                          ]
                                                        ]
                                                      ]
                                                    ]
                                                  ]
                                                ]
                                              ]
                                            ]
                                          ]
                                        ]
                                      ]
                                    ]
                                  ]
                                ]
                              ]
                            ]
                          ]
                        ]
                      ]
                    ]
                  ]
                ]
              ]
            ]
          ]
        ]
      ]
    ]
  ]
];

var crankLengths = /* :: */[
  150,
  /* :: */[
    152,
    /* :: */[
      155,
      /* :: */[
        158,
        /* :: */[
          160,
          /* :: */[
            162.5,
            /* :: */[
              165,
              /* :: */[
                167.5,
                /* :: */[
                  170,
                  /* :: */[
                    172.5,
                    /* :: */[
                      175,
                      /* :: */[
                        177.5,
                        /* :: */[
                          180,
                          /* :: */[
                            185,
                            /* :: */[
                              190,
                              /* [] */0
                            ]
                          ]
                        ]
                      ]
                    ]
                  ]
                ]
              ]
            ]
          ]
        ]
      ]
    ]
  ]
];

exports.chainringTeeth = chainringTeeth;
exports.cogTeeth = cogTeeth;
exports.wheelSizes = wheelSizes;
exports.crankLengths = crankLengths;
/* chainringTeeth Not a pure module */
