// Generated by BUCKLESCRIPT VERSION 5.0.0, PLEASE EDIT WITH CARE
'use strict';

var ReactDOMRe = require("reason-react/lib/js/src/ReactDOMRe.js");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var App$GearCalculator = require("./Components/App.bs.js");

ReactDOMRe.renderToElementWithId(ReasonReact.element(undefined, undefined, App$GearCalculator.make(/* array */[])), "app");

/*  Not a pure module */
