// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var $$String = require("bs-platform/lib/js/string.js");
var Caml_string = require("bs-platform/lib/js/caml_string.js");

function formatFloat(str) {
  var len = str.length;
  var lastChar = Caml_string.get(str, len - 1 | 0);
  if (lastChar === /* "." */46) {
    return $$String.sub(str, 0, len - 1 | 0);
  } else {
    return str;
  }
}

exports.formatFloat = formatFloat;
/* No side effect */
