// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var MaterialUi_Fab = require("@jsiebern/bs-material-ui/lib/js/src/MaterialUi_Fab.bs.js");
var MaterialUi_WithStyles = require("@jsiebern/bs-material-ui/lib/js/src/MaterialUi_WithStyles.bs.js");
var Add$MscharleyBsMaterialUiIcons = require("@mscharley/bs-material-ui-icons/lib/js/src/icons/Add.bs.js");

var component = ReasonReact.statelessComponent("AddNewButton-GearCalculator");

function classRecordToJs(param) {
  return {
          add: param[/* add */0]
        };
}

var classes = /* Record */Block.__(0, [/* record */[/* add */{
        bottom: "24px",
        position: "absolute",
        right: "36px"
      }]]);

function classRecordStringsFromJs(arg) {
  return /* record */[/* add */arg.add];
}

var StyleDefs = /* module */[
  /* classRecordToJs */classRecordToJs,
  /* classRecordStringsFromJs */classRecordStringsFromJs,
  /* classes */classes
];

var Style = MaterialUi_WithStyles.WithStylesSafe(StyleDefs);

function make(_children, onClick) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (_self) {
              return ReasonReact.element(undefined, undefined, Curry._1(Style[/* make */4], (function (classes) {
                                return ReasonReact.element(undefined, undefined, MaterialUi_Fab.make(classes[/* add */0], /* Primary */-791844958, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, onClick, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* array */[ReasonReact.element(undefined, undefined, Curry._7(Add$MscharleyBsMaterialUiIcons.Filled[/* make */1], undefined, undefined, undefined, undefined, undefined, undefined, /* array */[]))]));
                              })));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.component = component;
exports.StyleDefs = StyleDefs;
exports.Style = Style;
exports.make = make;
/* component Not a pure module */
