// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Pervasives = require("bs-platform/lib/js/pervasives.js");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var MaterialUi_Grid = require("@jsiebern/bs-material-ui/lib/js/src/MaterialUi_Grid.bs.js");
var Header$GearCalculator = require("./Header.bs.js");
var GearList$GearCalculator = require("./GearList.bs.js");
var HelpModal$GearCalculator = require("./HelpModal.bs.js");
var WindowSize$GearCalculator = require("./WindowSize.bs.js");
var AddNewButton$GearCalculator = require("./AddNewButton.bs.js");
var GearingModal$GearCalculator = require("./GearingModal.bs.js");
var GearCalculator$GearCalculator = require("./GearCalculator.bs.js");

var component = ReasonReact.reducerComponent("App-GearCalculator");

function make(_children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (self) {
              return ReasonReact.element(undefined, undefined, WindowSize$GearCalculator.make((function (dimensions) {
                                var isMobile = dimensions[/* width */0] < 768;
                                return React.createElement(React.Fragment, undefined, ReasonReact.element(undefined, undefined, Header$GearCalculator.make((function (_event) {
                                                      return Curry._1(self[/* send */3], /* ModalOpen */Block.__(1, [/* Help */1]));
                                                    }), /* array */[])), ReasonReact.element(undefined, undefined, HelpModal$GearCalculator.make(/* array */[], self[/* state */1][/* modal */0] === /* Help */1, (function (_event) {
                                                      return Curry._1(self[/* send */3], /* ModalClose */0);
                                                    }), isMobile)), ReasonReact.element(undefined, undefined, GearingModal$GearCalculator.make(/* array */[], self[/* state */1][/* modal */0] === /* Gearing */0, (function (_event) {
                                                      return Curry._1(self[/* send */3], /* ModalClose */0);
                                                    }), (function (gearing) {
                                                      return Curry._1(self[/* send */3], /* AddGearing */Block.__(0, [gearing]));
                                                    }), isMobile)), ReasonReact.element(undefined, undefined, MaterialUi_Grid.make(undefined, undefined, undefined, undefined, true, undefined, undefined, undefined, undefined, undefined, undefined, /* V0 */0, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* array */[
                                                    ReasonReact.element(undefined, undefined, MaterialUi_Grid.make(undefined, undefined, undefined, undefined, undefined, undefined, true, undefined, undefined, /* V3 */2, undefined, undefined, undefined, undefined, /* V12 */11, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* array */[ReasonReact.element(undefined, undefined, GearList$GearCalculator.make(dimensions, self[/* state */1][/* gearings */1], self[/* state */1][/* selectedGear */2], (function (gearing) {
                                                                          return Curry._1(self[/* send */3], /* SelectItem */Block.__(2, [gearing]));
                                                                        }), /* array */[]))])),
                                                    ReasonReact.element(undefined, undefined, GearCalculator$GearCalculator.make(self[/* state */1][/* selectedGear */2], (function (details) {
                                                                var match = self[/* state */1][/* selectedGear */2];
                                                                return ReasonReact.element(undefined, undefined, MaterialUi_Grid.make(undefined, undefined, undefined, undefined, undefined, undefined, true, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* V9 */8, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* array */[match !== undefined ? React.createElement(React.Fragment, undefined, Pervasives.string_of_float(match[/* wheelSize */3]), Pervasives.string_of_float(details[/* gearInches */0])) : "Create a gear to get started"]));
                                                              }), /* array */[]))
                                                  ])), ReasonReact.element(undefined, undefined, AddNewButton$GearCalculator.make(/* array */[], (function (_event) {
                                                      return Curry._1(self[/* send */3], /* ModalOpen */Block.__(1, [/* Gearing */0]));
                                                    }))));
                              }), /* array */[]));
            }),
          /* initialState */(function (param) {
              return /* record */[
                      /* modal : None */2,
                      /* gearings : [] */0,
                      /* selectedGear */undefined
                    ];
            }),
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */(function (action, state) {
              if (typeof action === "number") {
                return /* Update */Block.__(0, [/* record */[
                            /* modal : None */2,
                            /* gearings */state[/* gearings */1],
                            /* selectedGear */state[/* selectedGear */2]
                          ]]);
              } else {
                switch (action.tag | 0) {
                  case 0 : 
                      var gearing = action[0];
                      var match = List.length(state[/* gearings */1]) < 1;
                      return /* Update */Block.__(0, [/* record */[
                                  /* modal */state[/* modal */0],
                                  /* gearings */Pervasives.$at(state[/* gearings */1], /* :: */[
                                        gearing,
                                        /* [] */0
                                      ]),
                                  /* selectedGear */match ? gearing : state[/* selectedGear */2]
                                ]]);
                  case 1 : 
                      return /* Update */Block.__(0, [/* record */[
                                  /* modal */action[0],
                                  /* gearings */state[/* gearings */1],
                                  /* selectedGear */state[/* selectedGear */2]
                                ]]);
                  case 2 : 
                      return /* Update */Block.__(0, [/* record */[
                                  /* modal */state[/* modal */0],
                                  /* gearings */state[/* gearings */1],
                                  /* selectedGear */action[0]
                                ]]);
                  
                }
              }
            }),
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
