// Generated by BUCKLESCRIPT VERSION 5.0.0, PLEASE EDIT WITH CARE
'use strict';

var Cn = require("re-classnames/lib/js/src/Cn.bs.js");
var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var MaterialUi_Tab = require("@jsiebern/bs-material-ui/lib/js/src/MaterialUi_Tab.bs.js");
var MaterialUi_Grid = require("@jsiebern/bs-material-ui/lib/js/src/MaterialUi_Grid.bs.js");
var MaterialUi_Tabs = require("@jsiebern/bs-material-ui/lib/js/src/MaterialUi_Tabs.bs.js");
var MaterialUi_AppBar = require("@jsiebern/bs-material-ui/lib/js/src/MaterialUi_AppBar.bs.js");
var MaterialUi_WithStyles = require("@jsiebern/bs-material-ui/lib/js/src/MaterialUi_WithStyles.bs.js");
var ValueCard$GearCalculator = require("./ValueCard.bs.js");
var TabSection$GearCalculator = require("./TabSection.bs.js");

var component = ReasonReact.reducerComponent("GearDetailSection-GearCalculator");

function classRecordToJs(param) {
  return {
          container: param[/* container */0],
          row: param[/* row */1],
          tabSection: param[/* tabSection */2]
        };
}

var classes = /* Record */Block.__(0, [/* record */[
      /* container */{
        maxWidth: "100%",
        padding: "2.4em",
        textAlign: "center"
      },
      /* row */{
        paddingBottom: "2em"
      },
      /* tabSection */{
        backgroundColor: "#ffffff"
      }
    ]]);

function classRecordStringsFromJs(arg) {
  return /* record */[
          /* container */arg.container,
          /* row */arg.row,
          /* tabSection */arg.tabSection
        ];
}

var StyleDefs = /* module */[
  /* classRecordToJs */classRecordToJs,
  /* classRecordStringsFromJs */classRecordStringsFromJs,
  /* classes */classes
];

var Style = MaterialUi_WithStyles.WithStylesSafe(StyleDefs);

function make(gearing, details, _children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (self) {
              return ReasonReact.element(undefined, undefined, Curry._1(Style[/* make */4], (function (classes) {
                                var match = self[/* state */1][/* value */0];
                                return React.createElement("div", {
                                            className: classes[/* container */0]
                                          }, ReasonReact.element(undefined, undefined, MaterialUi_Grid.make(undefined, undefined, classes[/* row */1], undefined, true, undefined, undefined, undefined, undefined, undefined, undefined, /* V24 */3, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* array */[
                                                    ReasonReact.element(undefined, undefined, MaterialUi_Grid.make(undefined, undefined, undefined, undefined, undefined, undefined, true, undefined, undefined, /* V3 */2, undefined, undefined, undefined, undefined, /* V12 */11, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* array */[ReasonReact.element(undefined, undefined, ValueCard$GearCalculator.make(details[/* gearInches */0].toFixed(1), "Gear Inches", /* array */[]))])),
                                                    ReasonReact.element(undefined, undefined, MaterialUi_Grid.make(undefined, undefined, undefined, undefined, undefined, undefined, true, undefined, undefined, /* V3 */2, undefined, undefined, undefined, undefined, /* V12 */11, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* array */[ReasonReact.element(undefined, undefined, ValueCard$GearCalculator.make(details[/* development */1].toFixed(1), "Development", /* array */[]))])),
                                                    ReasonReact.element(undefined, undefined, MaterialUi_Grid.make(undefined, undefined, undefined, undefined, undefined, undefined, true, undefined, undefined, /* V3 */2, undefined, undefined, undefined, undefined, /* V12 */11, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* array */[ReasonReact.element(undefined, undefined, ValueCard$GearCalculator.make(details[/* gainRatio */2].toFixed(1), "Gain Ratio", /* array */[]))])),
                                                    ReasonReact.element(undefined, undefined, MaterialUi_Grid.make(undefined, undefined, undefined, undefined, undefined, undefined, true, undefined, undefined, /* V3 */2, undefined, undefined, undefined, undefined, /* V12 */11, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* array */[ReasonReact.element(undefined, undefined, ValueCard$GearCalculator.make(details[/* skidPatches */3].toString(), "Skid Patches", /* array */[]))]))
                                                  ])), ReasonReact.element(undefined, undefined, MaterialUi_Grid.make(undefined, undefined, Cn.make(/* :: */[
                                                        classes[/* row */1],
                                                        /* :: */[
                                                          classes[/* tabSection */2],
                                                          /* [] */0
                                                        ]
                                                      ]), undefined, true, undefined, undefined, undefined, undefined, undefined, undefined, /* V24 */3, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* array */[
                                                    ReasonReact.element(undefined, undefined, MaterialUi_AppBar.make(undefined, /* Default */-384499551, /* Static */982536398, undefined, undefined, undefined, undefined, undefined, /* array */[ReasonReact.element(undefined, undefined, MaterialUi_Tabs.make(undefined, undefined, undefined, undefined, /* Primary */-791844958, (function (_event, value) {
                                                                          return Curry._1(self[/* send */3], /* SelectTab */[value]);
                                                                        }), undefined, undefined, undefined, /* Primary */-791844958, undefined, self[/* state */1][/* value */0], /* Standard */-1003883683, undefined, undefined, /* array */[
                                                                        ReasonReact.element(undefined, undefined, MaterialUi_Tab.make(undefined, undefined, undefined, undefined, undefined, "Cadence Chart", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* array */[])),
                                                                        ReasonReact.element(undefined, undefined, MaterialUi_Tab.make(undefined, undefined, undefined, undefined, undefined, "Equivalent Gearing", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* array */[]))
                                                                      ]))])),
                                                    match !== 0 ? (
                                                        match !== 1 ? React.createElement("div", undefined) : ReasonReact.element(undefined, undefined, TabSection$GearCalculator.make(/* array */["Item Two "]))
                                                      ) : ReasonReact.element(undefined, undefined, TabSection$GearCalculator.make(/* array */["Item One"]))
                                                  ])));
                              })));
            }),
          /* initialState */(function (param) {
              return /* record */[/* value */0];
            }),
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */(function (action, _state) {
              return /* Update */Block.__(0, [/* record */[/* value */action[0]]]);
            }),
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.component = component;
exports.StyleDefs = StyleDefs;
exports.Style = Style;
exports.make = make;
/* component Not a pure module */
