// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var $$Array = require("bs-platform/lib/js/array.js");
var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var MaterialUi_List = require("@jsiebern/bs-material-ui/lib/js/src/MaterialUi_List.bs.js");
var MaterialUi_Typography = require("@jsiebern/bs-material-ui/lib/js/src/MaterialUi_Typography.bs.js");
var MaterialUi_WithStyles = require("@jsiebern/bs-material-ui/lib/js/src/MaterialUi_WithStyles.bs.js");
var MaterialUi_ListSubheader = require("@jsiebern/bs-material-ui/lib/js/src/MaterialUi_ListSubheader.bs.js");
var GearListItem$GearCalculator = require("./GearListItem.bs.js");

function classRecordToJs(param) {
  return {
          listHeading: param[/* listHeading */0]
        };
}

var classes = /* Record */Block.__(0, [/* record */[/* listHeading */{
        margin: "0.6em 0"
      }]]);

function classRecordStringsFromJs(arg) {
  return /* record */[/* listHeading */arg.listHeading];
}

var StyleDefs = /* module */[
  /* classRecordToJs */classRecordToJs,
  /* classRecordStringsFromJs */classRecordStringsFromJs,
  /* classes */classes
];

var Style = MaterialUi_WithStyles.WithStylesSafe(StyleDefs);

function getSectionHeight(windowHeight) {
  return String(windowHeight - 64 | 0);
}

function label(param) {
  return "" + (String(param[/* chainringTeeth */1]) + (" x " + (String(param[/* cogTeeth */2]) + "")));
}

function listGears(gearings) {
  return $$Array.of_list(List.map((function (gear) {
                    return ReasonReact.element(undefined, undefined, GearListItem$GearCalculator.make(gear, /* array */[]));
                  }), gearings));
}

function emptyList(l) {
  return List.length(l) === 0;
}

var component = ReasonReact.statelessComponent("GearList-GearCalculator");

function make(dimensions, gearings, _children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (_self) {
              return ReasonReact.element(undefined, undefined, Curry._1(Style[/* make */4], (function (classes) {
                                var match = List.length(gearings) === 0;
                                return ReasonReact.element(undefined, undefined, MaterialUi_List.make(undefined, /* `String */[
                                                -976970511,
                                                "nav"
                                              ], undefined, undefined, Caml_option.some(ReasonReact.element(undefined, undefined, MaterialUi_ListSubheader.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* array */[ReasonReact.element(undefined, undefined, MaterialUi_Typography.make(undefined, classes[/* listHeading */0], undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* H6 */16110, undefined, undefined, /* array */["Gears"]))]))), undefined, {
                                                backgroundColor: "#fff",
                                                height: String(dimensions[/* height */1] - 64 | 0) + "px",
                                                overflowY: "auto",
                                                padding: "0"
                                              }, /* array */[match ? ReasonReact.element(undefined, undefined, GearListItem$GearCalculator.NoItems[/* make */1](/* array */[])) : listGears(gearings)]));
                              })));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

var headerHeight = 64;

exports.headerHeight = headerHeight;
exports.StyleDefs = StyleDefs;
exports.Style = Style;
exports.getSectionHeight = getSectionHeight;
exports.label = label;
exports.listGears = listGears;
exports.emptyList = emptyList;
exports.component = component;
exports.make = make;
/* Style Not a pure module */
