// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Belt_List = require("bs-platform/lib/js/belt_List.js");
var Pervasives = require("bs-platform/lib/js/pervasives.js");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var MaterialUi_Button = require("@jsiebern/bs-material-ui/lib/js/src/MaterialUi_Button.bs.js");
var MaterialUi_Dialog = require("@jsiebern/bs-material-ui/lib/js/src/MaterialUi_Dialog.bs.js");
var MaterialUi_Select = require("@jsiebern/bs-material-ui/lib/js/src/MaterialUi_Select.bs.js");
var MaterialUi_Switch = require("@jsiebern/bs-material-ui/lib/js/src/MaterialUi_Switch.bs.js");
var MaterialUi_MenuItem = require("@jsiebern/bs-material-ui/lib/js/src/MaterialUi_MenuItem.bs.js");
var Util$GearCalculator = require("../Util.bs.js");
var MaterialUi_InputLabel = require("@jsiebern/bs-material-ui/lib/js/src/MaterialUi_InputLabel.bs.js");
var MaterialUi_WithStyles = require("@jsiebern/bs-material-ui/lib/js/src/MaterialUi_WithStyles.bs.js");
var MaterialUi_DialogTitle = require("@jsiebern/bs-material-ui/lib/js/src/MaterialUi_DialogTitle.bs.js");
var MaterialUi_DialogActions = require("@jsiebern/bs-material-ui/lib/js/src/MaterialUi_DialogActions.bs.js");
var MaterialUi_DialogContent = require("@jsiebern/bs-material-ui/lib/js/src/MaterialUi_DialogContent.bs.js");
var GearingValues$GearCalculator = require("../GearUtil/GearingValues.bs.js");
var MaterialUi_DialogContentText = require("@jsiebern/bs-material-ui/lib/js/src/MaterialUi_DialogContentText.bs.js");

var component = ReasonReact.reducerComponent("GearingModal-GearCalculator");

function classRecordToJs(param) {
  return {
          field: param[/* field */0]
        };
}

var classes = /* Record */Block.__(0, [/* record */[/* field */{
        marginBottom: "1.5em"
      }]]);

function classRecordStringsFromJs(arg) {
  return /* record */[/* field */arg.field];
}

var StyleDefs = /* module */[
  /* classRecordToJs */classRecordToJs,
  /* classRecordStringsFromJs */classRecordStringsFromJs,
  /* classes */classes
];

var Style = MaterialUi_WithStyles.WithStylesSafe(StyleDefs);

function getDefaultState(param) {
  return /* record */[/* gearing : record */[
            /* createdAt */Date.now() | 0,
            /* chainringTeeth */46,
            /* cogTeeth */16,
            /* wheelSize */27,
            /* crankLength */165,
            /* ambidextrousSkidder */false
          ]];
}

function make(_children, visible, handleClose, addGearing, fullScreen) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (self) {
              return ReasonReact.element(undefined, undefined, Curry._1(Style[/* make */4], (function (classes) {
                                return React.createElement(React.Fragment, undefined, ReasonReact.element(undefined, undefined, MaterialUi_Dialog.make(undefined, undefined, undefined, undefined, fullScreen, undefined, undefined, (function (_e) {
                                                      return Curry._1(self[/* send */3], /* CloseModal */0);
                                                    }), undefined, undefined, undefined, undefined, (function (_e) {
                                                      return Curry._1(self[/* send */3], /* CloseModal */0);
                                                    }), undefined, undefined, undefined, visible, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* array */[React.createElement("form", undefined, ReasonReact.element(undefined, undefined, MaterialUi_DialogTitle.make(undefined, undefined, undefined, undefined, /* array */["Enter your details"])), ReasonReact.element(undefined, undefined, MaterialUi_DialogContent.make(undefined, undefined, undefined, /* array */[
                                                                  ReasonReact.element(undefined, undefined, MaterialUi_DialogContentText.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, true, undefined, undefined, undefined, undefined, /* array */["Enter your component details below to calculate your gearing."])),
                                                                  ReasonReact.element(undefined, undefined, MaterialUi_InputLabel.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* array */["Chainring"])),
                                                                  ReasonReact.element(undefined, undefined, MaterialUi_Select.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, (function (e, _child) {
                                                                              return Curry._1(self[/* send */3], /* UpdateChainringTeeth */Block.__(0, [e.target.value]));
                                                                            }), undefined, undefined, undefined, undefined, undefined, /* `Float */[
                                                                            365180284,
                                                                            self[/* state */1][/* gearing */0][/* chainringTeeth */1]
                                                                          ], undefined, undefined, undefined, classes[/* field */0], undefined, undefined, undefined, undefined, undefined, true, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* array */[Belt_List.map(GearingValues$GearCalculator.chainringTeeth, (function (teeth) {
                                                                                    return ReasonReact.element(Pervasives.string_of_float(teeth), undefined, MaterialUi_MenuItem.make(undefined, undefined, undefined, undefined, undefined, /* `Float */[
                                                                                                    365180284,
                                                                                                    teeth
                                                                                                  ], undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* array */[React.createElement("em", undefined, Pervasives.string_of_float(teeth))]));
                                                                                  }))])),
                                                                  ReasonReact.element(undefined, undefined, MaterialUi_InputLabel.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* array */["Cog"])),
                                                                  ReasonReact.element(undefined, undefined, MaterialUi_Select.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, (function (e, _child) {
                                                                              return Curry._1(self[/* send */3], /* UpdateCogTeeth */Block.__(1, [e.target.value]));
                                                                            }), undefined, undefined, undefined, undefined, undefined, /* `Float */[
                                                                            365180284,
                                                                            self[/* state */1][/* gearing */0][/* cogTeeth */2]
                                                                          ], undefined, undefined, undefined, classes[/* field */0], undefined, undefined, undefined, undefined, undefined, true, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* array */[Belt_List.map(GearingValues$GearCalculator.cogTeeth, (function (teeth) {
                                                                                    return ReasonReact.element(Pervasives.string_of_float(teeth), undefined, MaterialUi_MenuItem.make(undefined, undefined, undefined, undefined, undefined, /* `Float */[
                                                                                                    365180284,
                                                                                                    teeth
                                                                                                  ], undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* array */[React.createElement("em", undefined, Pervasives.string_of_float(teeth))]));
                                                                                  }))])),
                                                                  ReasonReact.element(undefined, undefined, MaterialUi_InputLabel.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* array */["Wheel Size"])),
                                                                  ReasonReact.element(undefined, undefined, MaterialUi_Select.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, (function (e, _child) {
                                                                              return Curry._1(self[/* send */3], /* UpdateWheelSize */Block.__(2, [e.target.value]));
                                                                            }), undefined, undefined, undefined, undefined, undefined, /* `Float */[
                                                                            365180284,
                                                                            self[/* state */1][/* gearing */0][/* wheelSize */3]
                                                                          ], undefined, undefined, undefined, classes[/* field */0], undefined, undefined, undefined, undefined, undefined, true, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* array */[Belt_List.map(GearingValues$GearCalculator.wheelSizes, (function (param) {
                                                                                    return ReasonReact.element(param[/* key */2], undefined, MaterialUi_MenuItem.make(undefined, undefined, undefined, undefined, undefined, /* `Float */[
                                                                                                    365180284,
                                                                                                    param[/* value */1]
                                                                                                  ], undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* array */[React.createElement("em", undefined, param[/* name */0])]));
                                                                                  }))])),
                                                                  ReasonReact.element(undefined, undefined, MaterialUi_InputLabel.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* array */["Crank Length"])),
                                                                  ReasonReact.element(undefined, undefined, MaterialUi_Select.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, (function (e, _child) {
                                                                              return Curry._1(self[/* send */3], /* UpdateCrankLength */Block.__(3, [e.target.value]));
                                                                            }), undefined, undefined, undefined, undefined, undefined, /* `Float */[
                                                                            365180284,
                                                                            self[/* state */1][/* gearing */0][/* crankLength */4]
                                                                          ], undefined, undefined, undefined, classes[/* field */0], undefined, undefined, undefined, undefined, undefined, true, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* array */[Belt_List.map(GearingValues$GearCalculator.crankLengths, (function (length) {
                                                                                    return ReasonReact.element(Pervasives.string_of_float(length), undefined, MaterialUi_MenuItem.make(undefined, undefined, undefined, undefined, undefined, /* `Float */[
                                                                                                    365180284,
                                                                                                    length
                                                                                                  ], undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* array */[React.createElement("em", undefined, Util$GearCalculator.formatFloat(Pervasives.string_of_float(length)))]));
                                                                                  }))])),
                                                                  ReasonReact.element(undefined, undefined, MaterialUi_InputLabel.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* array */["Ambidextrous Skidder"])),
                                                                  ReasonReact.element(undefined, undefined, MaterialUi_Switch.make(/* `Bool */[
                                                                            737456202,
                                                                            self[/* state */1][/* gearing */0][/* ambidextrousSkidder */5]
                                                                          ], undefined, undefined, /* Primary */-791844958, undefined, undefined, undefined, undefined, undefined, undefined, undefined, (function (_e, checked) {
                                                                              return Curry._1(self[/* send */3], /* UpdateAmbidextrousSkidder */Block.__(4, [checked]));
                                                                            }), undefined, undefined, undefined, undefined, /* array */[]))
                                                                ])), ReasonReact.element(undefined, undefined, MaterialUi_DialogActions.make(undefined, undefined, undefined, undefined, /* array */[
                                                                  ReasonReact.element(undefined, undefined, MaterialUi_Button.make(undefined, /* Primary */-791844958, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, (function (_e) {
                                                                              return Curry._1(self[/* send */3], /* CloseModal */0);
                                                                            }), undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* array */["Cancel"])),
                                                                  ReasonReact.element(undefined, undefined, MaterialUi_Button.make(undefined, /* Primary */-791844958, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, (function (_e) {
                                                                              return Curry._1(self[/* send */3], /* SubmitGearing */1);
                                                                            }), undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* array */["Ok"]))
                                                                ])))])));
                              })));
            }),
          /* initialState */getDefaultState,
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */(function (action, state) {
              if (typeof action === "number") {
                if (action === 0) {
                  return /* UpdateWithSideEffects */Block.__(2, [
                            getDefaultState(/* () */0),
                            (function (_self) {
                                return Curry._1(handleClose, /* () */0);
                              })
                          ]);
                } else {
                  return /* UpdateWithSideEffects */Block.__(2, [
                            getDefaultState(/* () */0),
                            (function (_self) {
                                Curry._1(addGearing, state[/* gearing */0]);
                                return Curry._1(handleClose, /* () */0);
                              })
                          ]);
                }
              } else {
                switch (action.tag | 0) {
                  case 0 : 
                      var init = state[/* gearing */0];
                      return /* Update */Block.__(0, [/* record */[/* gearing : record */[
                                    /* createdAt */init[/* createdAt */0],
                                    /* chainringTeeth */action[0],
                                    /* cogTeeth */init[/* cogTeeth */2],
                                    /* wheelSize */init[/* wheelSize */3],
                                    /* crankLength */init[/* crankLength */4],
                                    /* ambidextrousSkidder */init[/* ambidextrousSkidder */5]
                                  ]]]);
                  case 1 : 
                      var init$1 = state[/* gearing */0];
                      return /* Update */Block.__(0, [/* record */[/* gearing : record */[
                                    /* createdAt */init$1[/* createdAt */0],
                                    /* chainringTeeth */init$1[/* chainringTeeth */1],
                                    /* cogTeeth */action[0],
                                    /* wheelSize */init$1[/* wheelSize */3],
                                    /* crankLength */init$1[/* crankLength */4],
                                    /* ambidextrousSkidder */init$1[/* ambidextrousSkidder */5]
                                  ]]]);
                  case 2 : 
                      var init$2 = state[/* gearing */0];
                      return /* Update */Block.__(0, [/* record */[/* gearing : record */[
                                    /* createdAt */init$2[/* createdAt */0],
                                    /* chainringTeeth */init$2[/* chainringTeeth */1],
                                    /* cogTeeth */init$2[/* cogTeeth */2],
                                    /* wheelSize */action[0],
                                    /* crankLength */init$2[/* crankLength */4],
                                    /* ambidextrousSkidder */init$2[/* ambidextrousSkidder */5]
                                  ]]]);
                  case 3 : 
                      var init$3 = state[/* gearing */0];
                      return /* Update */Block.__(0, [/* record */[/* gearing : record */[
                                    /* createdAt */init$3[/* createdAt */0],
                                    /* chainringTeeth */init$3[/* chainringTeeth */1],
                                    /* cogTeeth */init$3[/* cogTeeth */2],
                                    /* wheelSize */init$3[/* wheelSize */3],
                                    /* crankLength */action[0],
                                    /* ambidextrousSkidder */init$3[/* ambidextrousSkidder */5]
                                  ]]]);
                  case 4 : 
                      var init$4 = state[/* gearing */0];
                      return /* Update */Block.__(0, [/* record */[/* gearing : record */[
                                    /* createdAt */init$4[/* createdAt */0],
                                    /* chainringTeeth */init$4[/* chainringTeeth */1],
                                    /* cogTeeth */init$4[/* cogTeeth */2],
                                    /* wheelSize */init$4[/* wheelSize */3],
                                    /* crankLength */init$4[/* crankLength */4],
                                    /* ambidextrousSkidder */action[0]
                                  ]]]);
                  
                }
              }
            }),
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.component = component;
exports.StyleDefs = StyleDefs;
exports.Style = Style;
exports.getDefaultState = getDefaultState;
exports.make = make;
/* component Not a pure module */
