// Generated by BUCKLESCRIPT VERSION 5.0.0, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var Calculate$GearCalculator = require("../GearUtil/Calculate.bs.js");

var component = ReasonReact.statelessComponent("GearCalculator-GearCalculator");

var defaultGear = /* record */[
  /* gearInches */0.0,
  /* development */0.0,
  /* gainRatio */0.0,
  /* skidPatches */0,
  /* equivalentGears : [] */0,
  /* cadences : [] */0
];

function createGearing(gearing) {
  return /* record */[
          /* gearInches */Calculate$GearCalculator.gearInches(gearing),
          /* development */Calculate$GearCalculator.metresOfDevelopment(gearing),
          /* gainRatio */Calculate$GearCalculator.gainRatio(gearing),
          /* skidPatches */Calculate$GearCalculator.skidPatches(gearing) | 0,
          /* equivalentGears */Calculate$GearCalculator.equivalentGear(gearing),
          /* cadences */Calculate$GearCalculator.generateCadences(gearing)
        ];
}

function make(gearing, render, _children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (_self) {
              return Curry._1(render, gearing !== undefined ? createGearing(gearing) : defaultGear);
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.component = component;
exports.defaultGear = defaultGear;
exports.createGearing = createGearing;
exports.make = make;
/* component Not a pure module */
