// Generated by BUCKLESCRIPT VERSION 5.0.0, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var MaterialUi_AppBar = require("@jsiebern/bs-material-ui/lib/js/src/MaterialUi_AppBar.bs.js");
var MaterialUi_Toolbar = require("@jsiebern/bs-material-ui/lib/js/src/MaterialUi_Toolbar.bs.js");
var Logo$GearCalculator = require("./Logo.bs.js");
var MaterialUi_IconButton = require("@jsiebern/bs-material-ui/lib/js/src/MaterialUi_IconButton.bs.js");
var MaterialUi_Typography = require("@jsiebern/bs-material-ui/lib/js/src/MaterialUi_Typography.bs.js");
var MaterialUi_WithStyles = require("@jsiebern/bs-material-ui/lib/js/src/MaterialUi_WithStyles.bs.js");
var Help$MscharleyBsMaterialUiIcons = require("@mscharley/bs-material-ui-icons/lib/js/src/icons/Help.bs.js");

var component = ReasonReact.statelessComponent("Header-GearCalculator");

function classRecordToJs(param) {
  return {
          heading: param[/* heading */0]
        };
}

var classes = /* Record */Block.__(0, [/* record */[/* heading */{
        flexGrow: "1"
      }]]);

function classRecordStringsFromJs(arg) {
  return /* record */[/* heading */arg.heading];
}

var StyleDefs = /* module */[
  /* classRecordToJs */classRecordToJs,
  /* classRecordStringsFromJs */classRecordStringsFromJs,
  /* classes */classes
];

var Style = MaterialUi_WithStyles.WithStylesSafe(StyleDefs);

function make(onHelpClick, _children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (_self) {
              return ReasonReact.element(undefined, undefined, Curry._1(Style[/* make */4], (function (classes) {
                                return ReasonReact.element(undefined, undefined, MaterialUi_AppBar.make(undefined, undefined, /* Relative */260471020, undefined, undefined, undefined, undefined, undefined, /* array */[ReasonReact.element(undefined, undefined, MaterialUi_Toolbar.make(undefined, undefined, undefined, undefined, undefined, /* array */[
                                                          ReasonReact.element(undefined, undefined, Logo$GearCalculator.make(/* array */[])),
                                                          ReasonReact.element(undefined, undefined, MaterialUi_Typography.make(undefined, classes[/* heading */0], /* Inherit */-72987685, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* Title */594052472, undefined, undefined, /* array */["Gear Calculator"])),
                                                          ReasonReact.element(undefined, undefined, MaterialUi_IconButton.make(undefined, /* Inherit */-72987685, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, onHelpClick, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* array */[ReasonReact.element(undefined, undefined, Curry._7(Help$MscharleyBsMaterialUiIcons.Filled[/* make */1], undefined, undefined, undefined, undefined, undefined, undefined, /* array */[]))]))
                                                        ]))]));
                              })));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.component = component;
exports.StyleDefs = StyleDefs;
exports.Style = Style;
exports.make = make;
/* component Not a pure module */
