// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var MaterialUi_Button = require("@jsiebern/bs-material-ui/lib/js/src/MaterialUi_Button.bs.js");
var MaterialUi_Dialog = require("@jsiebern/bs-material-ui/lib/js/src/MaterialUi_Dialog.bs.js");
var MaterialUi_DialogTitle = require("@jsiebern/bs-material-ui/lib/js/src/MaterialUi_DialogTitle.bs.js");
var MaterialUi_DialogActions = require("@jsiebern/bs-material-ui/lib/js/src/MaterialUi_DialogActions.bs.js");
var MaterialUi_DialogContent = require("@jsiebern/bs-material-ui/lib/js/src/MaterialUi_DialogContent.bs.js");
var MaterialUi_DialogContentText = require("@jsiebern/bs-material-ui/lib/js/src/MaterialUi_DialogContentText.bs.js");

var component = ReasonReact.statelessComponent("HelpModal-GearCalculator");

function make(_children, visible, handleClose, fullScreen) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (_self) {
              return ReasonReact.element(undefined, undefined, MaterialUi_Dialog.make(undefined, undefined, undefined, undefined, fullScreen, undefined, undefined, (function (_event) {
                                return Curry._1(handleClose, /* () */0);
                              }), undefined, undefined, undefined, undefined, (function (_event) {
                                return Curry._1(handleClose, /* () */0);
                              }), undefined, undefined, undefined, visible, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* array */[
                              ReasonReact.element(undefined, undefined, MaterialUi_DialogTitle.make(undefined, undefined, undefined, undefined, /* array */["About Gear Calculator"])),
                              ReasonReact.element(undefined, undefined, MaterialUi_DialogContent.make(undefined, undefined, undefined, /* array */[
                                        ReasonReact.element(undefined, undefined, MaterialUi_DialogContentText.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, true, undefined, undefined, undefined, undefined, /* array */["This site was built by Richey Ryan, a programmer from Dublin Ireland. It is inspired by and based on the work of sheldonbrown.com."])),
                                        ReasonReact.element(undefined, undefined, MaterialUi_DialogContentText.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, true, undefined, undefined, undefined, undefined, /* array */["Fill out the form to see your gear inches, development in metres, gain ratio and skid patches calculated."])),
                                        ReasonReact.element(undefined, undefined, MaterialUi_DialogContentText.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, true, undefined, undefined, undefined, undefined, /* array */["You will also be able to see a cadence chart of your speed in miles per hour and kilometres per hour, depending on your RPM, as well as a list of equivalent gear ratios."])),
                                        ReasonReact.element(undefined, undefined, MaterialUi_DialogContentText.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, true, undefined, undefined, undefined, undefined, /* array */["The equilavent gear ratios are within one gear inch higher or lower than the original ratio to allow for a significant range of comparison."]))
                                      ])),
                              ReasonReact.element(undefined, undefined, MaterialUi_DialogActions.make(undefined, undefined, undefined, undefined, /* array */[ReasonReact.element(undefined, undefined, MaterialUi_Button.make(undefined, /* Primary */-791844958, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, (function (_event) {
                                                    return Curry._1(handleClose, /* () */0);
                                                  }), undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* array */["Ok"]))]))
                            ]));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
