// Generated by BUCKLESCRIPT VERSION 5.0.0, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var MaterialUi_Typography = require("@jsiebern/bs-material-ui/lib/js/src/MaterialUi_Typography.bs.js");
var MaterialUi_WithStyles = require("@jsiebern/bs-material-ui/lib/js/src/MaterialUi_WithStyles.bs.js");

var component = ReasonReact.statelessComponent("TabSection-GearCalculator");

function classRecordToJs(param) {
  return {
          section: param[/* section */0]
        };
}

var classes = /* Record */Block.__(0, [/* record */[/* section */{
        padding: "1.5em"
      }]]);

function classRecordStringsFromJs(arg) {
  return /* record */[/* section */arg.section];
}

var StyleDefs = /* module */[
  /* classRecordToJs */classRecordToJs,
  /* classRecordStringsFromJs */classRecordStringsFromJs,
  /* classes */classes
];

var Style = MaterialUi_WithStyles.WithStylesSafe(StyleDefs);

function make(children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (_self) {
              return ReasonReact.element(undefined, undefined, Curry._1(Style[/* make */4], (function (classes) {
                                return ReasonReact.element(undefined, undefined, MaterialUi_Typography.make(undefined, classes[/* section */0], undefined, /* `String */[
                                                -976970511,
                                                "div"
                                              ], undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* array */[children]));
                              })));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.component = component;
exports.StyleDefs = StyleDefs;
exports.Style = Style;
exports.make = make;
/* component Not a pure module */
